baseURL = ""
languageCode = "en-us"
title = "Integreatly Website"
relativeURLs = true
disablePathToLower = true

[params]
    recent_posts_number = 10

[menu]

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Docs"
  weight = 2
  identifier = "docs"
  url = "/home/latest/index.html"

[[menu.main]]
  name = "About Docs"
  weight = 1
  identifier = "about"
  url = "/home/latest/index.html"
  parent = "docs"

[[menu.main]]
  name = "Syndesis"
  weight = 1
  identifier = "syndesis"
  url = "/syndesis/latest/index.html"
  parent = "docs"

[[menu.main]]
  name = "EnMasse"
  weight = 1
  identifier = "enmasse"
  url = "/enmasse/latest/master-openshift.html"
  parent = "docs"

[[menu.main]]
  name = "AeroGear"
  weight = 2
  identifier = "aerogear"
  url = "/aerogear/latest/getting-started.html"
  parent = "docs"


[[menu.main]]
  name = "Getting Started"
  weight = 2
  identifier = "gs"
  url = "/integreatly/latest/getting-started.html"
  parent = "docs"


[[menu.main]]
  name = "Release Notes"
  weight = 2
  identifier = "rn"
  url = "/integreatly/latest/release-notes.html"
  parent = "docs"



[[menu.main]]
  name = "Community"
  weight = 3
  identifier = "comm"
  url = "/i8y-community/"

[[menu.main]]
  name = "Contributing"
  weight = 1
  identifier = "contributing"
  url = "/i8y-community/contributing/"
  parent = "comm"

[[menu.main]]
  name = "Team"
  weight = 2
  identifier = "team"
  url = "/i8y-community/team/"
  parent = "comm"

[[menu.main]]
  name = "News"
  weight = 4
  identifier = "news"
  url = "/news/"
