site:
  title: Integreatly Docs
  start_page: home::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
    - url: https://github.com/aerogear/mobile-docs.git
      branches: master

ui:
  bundle:
    url: ./i8y-ui-bundle/build/ui-bundle.zip

urls:
  redirect_facility: disabled

output:
  dir: ./static
